### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by HoneyBearc** [mmopluginteam/mmocore#82]
Seems incompatible with "Residence"

[Server thread/WARN]: [MMOCore] Loaded class com.bekvon.bukkit.residence.protection.FlagPermissions from Residence v4.9.1.0 which is not a depend, softdepend or loadbefore of this plugin.
[Server thread/ERROR]: Error occurred while enabling MMOCore v1.4.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.protection.FlagPermissions.addFlag(FlagPermissions.java:98) ~[?:?]
	at net.Indyuce.mmocore.comp.flags.ResidenceFlags.<init>(ResidenceFlags.java:13) ~[?:?]
	at net.Indyuce.mmocore.MMOCore.onEnable(MMOCore.java:188) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-8918ad0-7a9e4f7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Joshinn-mc** [comment]
We will look into fixing this on our end, for now you can temporarily solve this by adding "Residence" as a Depend inside of the MMOCore plugin.yml which you can access bny right clicking the jar and opening with WinRAR.

**Comment by Indyuce** [comment]
Will be fixed in the next dev build
